### PR TITLE
Support re-include syntax. Fix #8

### LINKED ISSUE #8: Exclude file/directory
You write the .atomignore is working like the .gitignore, but when I add something like this:

```
libraries
!libraries/libtoshow
```

`libraries/libtoshow` should be visible and all other files/directories in `libraries` should be hidden.

### PR DESCRIPTION
**Pull request by PhiLhoSoft**
ignore library is a bit more permissive than git, I think.
See http://philhosoft.github.io/Software/Git%20gitignore%20rules/ where I checked rules for Git 2.7 (on Windows).

### CODE REVIEW

**Comment by leny** [comment]
Thanks for your interest in this package :+1: 

I'll try to merge & publish that tonight.

**Comment by leny** [comment]
Merge & published in `0.6.0`.
Thanks again.

**Comment by PhiLhoSoft** [comment]
> Thanks for your interest in this package :+1:

Honestly, it is not a major / high priority package for me (from a Atom user point of view), but I found it easy to hack on: simple, short, clean, and in JS, instead of CoffeeScript. So it was a great way to learn tricks on how to make an Atom package, and I learned a lot while hacking on this project.
So, thanks to you.

**Comment by leny** [comment]
You're welcome :smile:

**Pull request merged**
